version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest-browsers

jobs:
  validate:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - run:
          name: Run validate
          command: npm run validate.ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access=public

  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run validate.ci

      - store_artifacts:
          path: dist

workflows:
  version: 2
  test-deploy:
    jobs:
      - validate:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - validate
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/