/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GxgBaseComponentTemplate {
    /**
    * The kind of base-component-template Possible values: primary, secondary.
    */
    'type': string;
  }
  interface GxgButton {
    /**
    * The state of the button. Whether is disabled or not. Possible values: false, true
    */
    'disabled': boolean;
    /**
    * The kind of button Possible values: primary, secondary, text-only, icon-only
    */
    'type': string;
  }
}

declare global {


  interface HTMLGxgBaseComponentTemplateElement extends Components.GxgBaseComponentTemplate, HTMLStencilElement {}
  var HTMLGxgBaseComponentTemplateElement: {
    prototype: HTMLGxgBaseComponentTemplateElement;
    new (): HTMLGxgBaseComponentTemplateElement;
  };

  interface HTMLGxgButtonElement extends Components.GxgButton, HTMLStencilElement {}
  var HTMLGxgButtonElement: {
    prototype: HTMLGxgButtonElement;
    new (): HTMLGxgButtonElement;
  };
  interface HTMLElementTagNameMap {
    'gxg-base-component-template': HTMLGxgBaseComponentTemplateElement;
    'gxg-button': HTMLGxgButtonElement;
  }
}

declare namespace LocalJSX {
  interface GxgBaseComponentTemplate extends JSXBase.HTMLAttributes<HTMLGxgBaseComponentTemplateElement> {
    /**
    * The kind of base-component-template Possible values: primary, secondary.
    */
    'type'?: string;
  }
  interface GxgButton extends JSXBase.HTMLAttributes<HTMLGxgButtonElement> {
    /**
    * The state of the button. Whether is disabled or not. Possible values: false, true
    */
    'disabled'?: boolean;
    /**
    * The kind of button Possible values: primary, secondary, text-only, icon-only
    */
    'type'?: string;
  }

  interface IntrinsicElements {
    'gxg-base-component-template': GxgBaseComponentTemplate;
    'gxg-button': GxgButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


